name: code_testing

# Controls when the action will run.
on: [push, workflow_dispatch]

jobs:
  build_test:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - CC: "clang-10"
            CXX: "clang++-10"
          - CC: "gcc-10"
            CXX: "g++-10"
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # setup
      - name: install needed packages
        run: sudo apt-get -qq update && sudo apt-get -qq install -y git make cmake gcc-10 g++-10 clang-10 libstdc++-10-dev
      # build
      - name: build tests
        run: mkdir build && cd build && cmake -Ddice_hash_BUILD_TESTS=ON .. && make -j
        env:
          CC: ${{ matrix.CC }}
          CXX: ${{ matrix.CXX }}
      # execute
      - name: run tests
        run: build/tests/tests_dice_hash

  build_docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: build image
        run: docker build -t dockerimage .

      - name: run image
        run: docker run dockerimage