name: conan_upload

# idea: run on every push connected to a tag
on:
  push:
    tags:
    - 'v*'

jobs:
  test_variables:
    runs-on: ubuntu-20.04
    steps:
      - name: print interesting variables
        run: echo $GITHUB_REF