name: conan_upload

# idea: run on every push connected to a tag
on:
  push
#  push:
#    tags:
#    - '*'

jobs:
  build_and_upload:
    runs-on: ubuntu-20.04
    steps:
      - name: Install conan
        run: sudo apt-get update -qq && sudo apt-get install -qq python3 python3-pip -y && sudo pip3 install conan
      - name: Checkout
        uses: actions/checkout@v1
        # set the remote and login into the user
      - name: setup conan
        run: |
          conan remote add dice-group https://api.bintray.com/conan/dice-group/tentris
          conan user -p ${{ secrets.BINTRAY_API_KEY }} -r dice-group ${{ secrets.BINTRAY_USER }}
      - name: build the package
        run: conan create . "dice-group/stable" --build missing
        # will use `grep` and `sed` to extract the version number out of the cmake file
      - name: upload the package
        run: |
          VERSION=$(grep '^project(.*)$' CMakeLists.txt | sed 's/.*VERSION[[:blank:]]*//g;s/[[:blank:]]*).*//g')
          echo "$VERSION"
          conan remove "dice-hash/${VERSION}@dice-group/stable" -r dice-group -f
          conan upload "dice-hash/${VERSION}@dice-group/stable" --force --all -r dice-group --skip-upload