name: Detect POBR diff

on: [ pull_request ]

concurrency:
  group: detect-pobr-diff-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  detect-pobr-diff:
    uses: dice-group/cpp-conan-release-reusable-workflow/.github/workflows/abi-diff.yml@v2.0.5
    with:
      os: ubuntu-24.04
      setup_tools: true
      cc: clang-17
      cxx: clang++-17
      cmake-version: 4.4.2
      conan-version: 2.31.2
      base-branch: ${{ github.base_ref }}
      search-path: >
        include/dice/hash/internal
        include/dice/hash/blake
        include/dice/hash/lthash
      abi-version-header: include/dice/hash/version.hpp
      abi-version-const: dice::hash::pobr_version
    secrets:
      CONAN_CICD_ENDPOINT: ${{ secrets.CONAN_CICD_ENDPOINT }}