name: documentation

on:
  push:
    branches:
      - main

concurrency:
  group: publish-conan-branch-package-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  generate_doxygen_docu:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      # https://github.com/marketplace/actions/doxygen-action
      - name: generate docu
        uses: mattnotmitt/doxygen-action@v1.9.8
        with:
          working-directory: '.'
          doxyfile-path: 'Doxyfile'

      - name: upload to github page branch
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docu

