name: single_header_file

# only run for releases
on:
  release:
    types:
      - created

jobs:
  create_and_upload_file:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      # get needed packages
      - name: install needed packages
        run: |
          sudo apt-get -qq update && sudo apt-get -qq install -y python3 python3-pip
          sudo pip3 install quom
      # create the file
      - name: create the header file
        run: quom include/Dice/hash/DiceHash.hpp DiceHashSingleHeader.hpp -I include/
      #upload as artifact for testing purposes
      - name: upload as artifact
        uses: actions/upload-artifact@v2
        with:
          name: DiceHashSingleHeader.hpp
          path: DiceHashSingleHeader.hpp

      - name: test different env variables
        run: |
          echo GITHUB_EVENT_NAME $GITHUB_EVENT_NAME
          echo GITHUB_EVENT_PATH $GITHUB_EVENT_PATH
          echo GITHUB_REF $GITHUB_REF
      # does not working at the moment
#      - name: upload as asset
#        uses: actions/upload_release-asset@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          upload_url: ""
#          asset_path: DiceHashSingleHeader.hpp
#          asset_name: DiceHashSingleHeader.hpp
